# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.9.16 # https://pyreadiness.org/3.9

  # DEV dependencies
  - pytest=7.4.0
  - python-dotenv=1.0.0

  - pip=22.1.2 # https://pip.pypa.io/en/stable/news
  - pip:
      - robocorp==0.9.0 # https://pypi.org/project/robocorp
      - robocorp-browser==2.1.0 # https://pypi.org/project/robocorp-browser
