name: Test Robocorp Python Project

on:
  pull_request:
    branches:
      - main
      - test
      - dev
  workflow_call:

jobs:
  call-robocorp-install-dependencies:
    uses: ./.github/workflows/robocorp-install-dependencies.yml
  test:
    needs: call-robocorp-install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.robocorp
            /usr/local/bin/rcc
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/robot.yaml', '**/conda.yaml') }}

      - name: Run tests
        run: |
          rcc run -t "UNIT TESTS"
